### ISSUE TITLE
Detect double tracking

### ISSUE THREAD

**Issue by eduardocereto** [CardinalPath/gas#1]
Right now if you call most of the filters multiple times they may issue multiple event bindings resulting on multiple hits been sent to GA. 

We better flag if a tracking already happened and drop that instead.

In addition to that it would be nice to be able to call _trackYotutube or _trackVimeo multiple times to find videos added by ajax. There's a common use case of people using videos inside lightbox.

**Comment by phms** [comment]
Digital Cube's team is working to correct this error.

**Comment by eduardocereto** [comment]
Hey @phms I need this very soon to release 1.4 
Do you mind sharing your progress? Do you have any ETA?

**Comment by eduardocereto** [comment]
@phms I'm assigning myself to this issue because I want to deploy 1.4 later this week.

**Comment by tomfuertes** [comment]
All the current plugins conform to this standard.
