### ISSUE TITLE
Clicking link: el is undefined

### ISSUE THREAD

**Issue by gustin** [CardinalPath/gas#18]
I receive the following error when I add on any link when I track _trackOutboundLinks, _trackDownloads, or _trackMailto 

_trackPageview, _trackForms, and _trackMaxScroll seem to work fine. 

![Error](https://img.skitch.com/20120304-jg425ymw2psax569ruqcrbtybc.jpg)

``` javascript
for (var el = me.srcElement; el.nodeName !== 'HTML';
```

I am loading jQuery and some other scripts as well, could it be a load timing issue? 

Full script I am including:

``` javascript
   var _gas = _gas || [];
   _gas.push(['_setAccount', 'UA-23636765-1']);
   _gas.push(['_setDomainName', '.seedleaf.com']);

  _gas.push(['_trackPageview']);
  _gas.push(['_trackForms']);
  _gas.push(['_trackOutboundLinks']);
  _gas.push(['_trackMaxScroll']);
  _gas.push(['_trackDownloads']);
  _gas.push(['_trackMailto']);
  (function() {
    var ga = document.createElement('script');
    ga.type = 'text/javascript';
    ga.async = true;
    ga.src = 'javascripts/shared/gas.js';
    var s = document.getElementsByTagName('script')[0];
    s.parentNode.insertBefore(ga, s);
   })();
```

**Comment by gustin** [comment]
Great, thanks for the speedy turnaround!

**Comment by eduardocereto** [comment]
@gustin Thanks for opening this bug request. And feel free to open others if you find more problems.
