### ISSUE TITLE
gas _setDomainName questions

### ISSUE THREAD

**Issue by KarinaLibrary** [CardinalPath/gas#21]
Question / When using the gas MultiTrack feature, does _gas.push(['_setDomainName', 'myothersite.com']); also catch any linked subdomains? Eg, a link to blog.myothersite.com? 

Does the first _setDomainName showup as the domain label in GA reports?

**Comment by eduardocereto** [comment]
> Question / When using the gas MultiTrack feature, does _gas.push(['_setDomainName', 'myothersite.com']); also catch any linked subdomains? Eg, a link to blog.myothersite.com?

Yes

> Does the first _setDomainName showup as the domain label in GA reports?

GAS takes over `_setDomainName`. It will only push to `_gaq` the first domain name that is part of the url. 
So if your url is `www.example.com` and you push:

``` javascript
    _gas.push(['_setDomainName', 'mysite.com']);
    _gas.push(['_setDomainName', 'example.com']);
    _gas.push(['_setDomainName', 'www.example.com']);
```

`'example.com'` will be pushed into `_gaq` as the domain name and the other ones will be used for crossDomain.
