### ISSUE TITLE
Negative event values do not work

### ISSUE THREAD

**Issue by chhib** [CardinalPath/gas#38]
There is a line that says if the fourth argument of the event is negative, set it to 0. This is bad in this use case: Cart value tracking. People add and remove from the cart. Removing is an event with a negative value. Using the total and average value columns of the events reports you can see the aggregate cart values.

With GAS setting negative values to zero, this tracking is impossible. Should be corrected to allow for negative event values.

**Comment by eduardocereto** [comment]
In the past negative value events were bugged and were doing iteger overflow. So a -1 value was actualy close to 4 Billion on the reports. Maybe that has been fixed.

I've seen negative values working fine on transactions, but I've never seen it working on Events.

I'll confirm and change GAS
