### ISSUE TITLE
Enhanced Link Attribution

### ISSUE THREAD

**Issue by tomfuertes** [CardinalPath/gas#40]
Google Docs: https://support.google.com/analytics/bin/answer.py?hl=en&utm_id=ad&answer=2558867

Willing to implement, just filing an issue to here your thoughts on:
- Should this be handled through something like `_gas.push(['_gasEnhancedLinkAttribution']);`
-  Should it be left to the user per `_gas.push(['_require', 'inpage_linkid', '//www.google-analytics.com/plugins/ga/inpage_linkid.js']);`

**Comment by eduardocereto** [comment]
This one works just fine. I don't see the point in adding a wrapper to it.

```
_gas.push(['_require', 'inpage_linkid', '//www.google-analytics.com/plugins/ga/inpage_linkid.js']);
```
