### ISSUE TITLE
Support for Enhanced Link Attribution

### ISSUE THREAD

**Issue by beatever** [CardinalPath/gas#42]
Can there be support for Enhanced Link Attribution? I'm not technical, but I think GAS will need an adaptation? http://support.google.com/analytics/bin/answer.py?hl=en&hlrm=nl&answer=2558867

**Comment by thompsonpaul** [comment]
Dropped by to ask for this same addition. Enhanced Link Attribution is a major improvement and vastly reduces the necessity for custom coding variable into multiple links on pages.

I've tried adding the code to the existing implementation a number of ways with no success.

**Comment by caiomaccord** [comment]
Hi there. The same here. Could you add support for Enhanced Link Attribution?

**Comment by deizel** [comment]
Relates to #40

**Comment by caiomaccord** [comment]
Thanks Chris.

May you add this to the GAS README.md ?

2013/1/24 Chris Burke notifications@github.com

> Relates to #40 https://github.com/CardinalPath/gas/issues/40
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/CardinalPath/gas/issues/42#issuecomment-12664326.

## 

Caio Mac Cord
facebook.com/caiomaccord
br.linkedin.com/in/caiomaccord
