### ISSUE TITLE
Trying to track same page anchor links

### ISSUE THREAD

**Issue by kelicia** [CardinalPath/gas#48]
Can I use _gas.push(['_trackPageview', location.pathname + location.search + location.hash]);
like
_gaq.push(['_trackPageview', location.pathname + location.search + location.hash]);

or is there a better way to track anchor links with GAS?

**Comment by tomfuertes** [comment]
Once _gas gets done with any of the pushes it sends them to _gaq.

So yes, this works.

**Comment by kelicia** [comment]
Thanks!
