### ISSUE TITLE
Errormessages in Chrome Developer tools console

### ISSUE THREAD

**Issue by searchim** [CardinalPath/gas#49]
Hi,

Data in analytics seems fine, but receiving various errormessages in chrome developers tools console for the trackforms, maxscroll and outbound links on site www.uretek.nl

Example:

---

Called method "_gasTrackForms" threw exception.TypeError: Cannot call method 'apply' of undefined  
log 
N 
G.S 
G.push  
a.(anonymous function)  
v 
p._execute 
(anonymous function) 
G.S 
G.push 
a.(anonymous function) 
(anonymous function) 
$e 
a 
(anonymous function) 
(anonymous function)

---

Any suggestions on these errors?

**Comment by dbarlett** [comment]
What OS and version of Chrome are you using? I went to www.uretek.nl and clicked the YouTube link - the maxscroll and outbound events were sent to GA, and no errors appeared in the console.

**Comment by searchim** [comment]
Version Versie 29.0.1547.57 m f chrome and OS = Windows 7.
I am getting these errors in the console while using GA Debugger, that could be the problem perhaps.

**Comment by tomfuertes** [comment]
Fixed in 1.11.0
