### ISSUE TITLE
Problem loading in-page analytics

### ISSUE THREAD

**Issue by vossavant** [CardinalPath/gas#52]
We've been using your script without issue for some weeks now, but just last week, when signing into Analytics, we receive an error message:

![error](https://f.cloud.github.com/assets/1006875/1377092/6a759ade-3aa0-11e3-9a6e-19dc7c1c9a21.png)

There doesn't appear to have been any updates from your end lately, and to my knowledge no one has changed the code on the live site. I verified that the tracking number and domain in your snippet are correct.

The domain in question is www.trustamerica.com.

Do you know what the problem is?

**Comment by tomfuertes** [comment]
1.10.0 script is on cloudfare and unchanged. GA might have updated their scrape code to search the html for google's ga.js file.  You aren't loading the "in page analytics" plugin though if that's what you're trying to view: https://support.google.com/analytics/answer/2558867?hl=en&ref_topic=2558810

**Comment by vossavant** [comment]
Hi Tom,

Thanks for that quick reply. I added the in page analytics plugin, but to no avail. The error continues. I added the Google Analytics debugging extension for Chrome and discovered a few JS errors, which you can see in the attached screenshot.

![error-js](https://f.cloud.github.com/assets/1006875/1393300/2096bba4-3c18-11e3-873a-ea2d610df0c5.png)

Any ideas?
