### ISSUE TITLE
Problem loading in-page analytics (follow up)

### ISSUE THREAD

**Issue by vossavant** [CardinalPath/gas#53]
This is in reference to a closed issue: https://github.com/CardinalPath/gas/issues/52

It was closed prematurely, IMO, since the issue was not resolved. Forgive me for being persistent, but I figured that closed issues are not monitored, so it would make sense to post a new issue.

I added the in page analytics plugin, but to no avail. The error continues. I added the Google Analytics debugging extension for Chrome and discovered a few JS errors, which you can see in the attached screenshot.

![error-js](https://f.cloud.github.com/assets/1006875/1393300/2096bba4-3c18-11e3-873a-ea2d610df0c5.png)

Any ideas?

**Comment by tomfuertes** [comment]
These are referenced/fixed in this issue. The code is not currently in 1.10.0, but should go out in 1.11.0 https://github.com/CardinalPath/gas/issues/39

-Tom
