### ISSUE TITLE
extract script parts 

### ISSUE THREAD

**Issue by simonmadsen** [CardinalPath/gas#56]
can any describe in short how to only use the vimeo tracking part of the code for example? (extract it so to say)
and with universal analytics is preferrable.

I tried several vimeo tracking suggestions but GAS works best out of the box and I did not get others working yet.

we do not need pageview, downloads and etc. since we already have tracking on this.

It can maybe be a good idea to have a general guide for how to 'extract' code parts

The customer in mind already has universal analytics tracking which is why we would like the vimeo tracking to be as well.

**Comment by tomfuertes** [comment]
GAS does not currently have any plans to support extractable/modular plugins.  Each of the plugins does have it's own file in ./src/plugins/ though. 

You can either have the client install GAS and only paste in the _gasTrackVimeo line of the implementation or compile your own ./src/plugins/vimeo.js file if they have dev resources.

Good luck!
