### ISSUE TITLE
Integrate with Airlock for transitioning to analytics.js ?

### ISSUE THREAD

**Issue by googleanalyticsresoneo** [CardinalPath/gas#60]
Hi

This project emerged recently https://github.com/SDITools/Airlock and allows to use analytics.js without changing the tracking code.
Not tested but could be interesting to activate as an option in _gas ?!

Olivier

**Comment by tomfuertes** [comment]
Interesting project!  No plans to permanently merge it into core, but here's a custom build if you'd like to give it a spin: https://gist.github.com/tomfuertes/dd226427facdd128c822

**Comment by tomfuertes** [comment]
Closing this as we won't be integrating it into core. Looks like the build I posted above needs more updates from Airlock.js to fully integrate with GAS. GAS does some advanced cross domain _gat stuff that Airlock.js doesn't support yet.
