### ISSUE TITLE
after upgrade to GAS, visits counted but no pageviews, 0% bounce rate, Landing Pages not set

### ISSUE THREAD

**Issue by KarinaLibrary** [CardinalPath/gas#68]
For all visits, not just visits with events, no landing page, no pageviews, no bounce rate. 

This is using `_MultiDomain`. `utm_a` visitor value seems to pass correctly from site to site. Can see adwords conversions across domains to shopping cart subdomain. But no pageviews, and all Landing Pages are (not set). At first I thought this had to do with event tracking causing problems with pageviews, but not so sure. I can see the beacon fire, and the console shows it is sending the right uri. Baffled.

**Comment by KarinaLibrary** [comment]
OK. So, looks like part of the issue (two overlapping causes) is that the advanced filter that you find recommended by Google (and elsewhere) for cross domain where you take `Hostname` -> `$A1` and `Request URI` to `$B1` and then overwrite `Request URI` with `$A1$B1` was causing the issue. It seems wrapping the `.*` is not optional though I think it was in the past because it is the only value in the field. Removing the filter immediately brought back the landing pages and page views, but at least from early Real Time reports, wrapping `(.*)` also makes everything work as expected.

Some Events still causing `Landing Page` to be `(not set)`.  Need to do some further looking to make sure I changed all the `_gaq` occurrences to`_gas`. Wonder also if this new issue I saw this morning could be related as well: https://github.com/CardinalPath/gas/issues/69.

**Comment by googleanalyticsresoneo** [comment]
A suggestion: on which UA-XXX-YY do the hit fire ? The value you are expecting or UA-XXXXX-XX actually because _setAccount comes in too late ?

**Comment by tomfuertes** [comment]
Landing pages aren't shared between accounts and if it's an old visit it might be that the rollup reporting isn't being shared between the profiles? I don't know there are a lot of variables going on here that get more intricate that the ticket is allowing me to help. Happy to look over a pull request if you find the underlying bug. Other than that we should be using emails for this debugging and not github issues.
