### ISSUE TITLE
Doc questions

### ISSUE THREAD

**Issue by KarinaLibrary** [CardinalPath/gas#7]
Hey Eduardo - 

Wondering how I would "translate" this GATC into GAS (with cross domain tracking for domain1, domain2 on the UA-yyyyyyyy-y account) : 

  _gaq.push(['o._setAccount', 'UA-xxxxxxxx-x']); // old legacy id retained for data reasons
  _gaq.push(['o._trackPageview']);
  _gaq.push(['xd._setAccount', 'UA-yyyyyyyy-y']); // id for cross domain tracking
  _gaq.push(['xd._setDomainName', 'domain1.com']);
  _gaq.push(['xd._addIgnoredRef', 'domain1.com']);
  _gaq.push(['xd._setAllowAnchor', true]); // needed on the cross domain tracking only
  _gaq.push(['xd._setAllowLinker', true]);
  _gaq.push(['xd._trackPageview']);

Would it look like: 

   _gas.push(['o._setAccount', 'UA-xxxxxxxx-x']);
   _gas.push(['o._trackPageview']);
   _gas.push(['xd._setAccount', 'UA-yyyyyyyy-y']);
   _gas.push(['xd._setAllowAnchor', true]);
   _gas.push(['xd._setAllowLinker', true]);
   _gas.push(['xd._setDomainName', 'domain1.com']);
   _gas.push(['xd._setDomainName', 'domain2.com']);
   _gas.push(['xd._setMultiDomain', 'click']);
   _gas.push(['xd._trackPageview']);

How to handle addIgnoredRef, since setDomainName is being used to add domains into the cross-domain tracking? Maybe not that important. Is claimed to reduce self-referrals, but may not be needed.

**Comment by eduardocereto** [comment]
I don't really use `_addIgnoredRef` anymore for this kind of stuff. But you can use if you want, It won't affect the x-domain tracking.

I'd write that down like this:

``` javascript
_gas.push(['_setAccount', 'UA-xxxxxxxx-x']);
_gas.push(['_setAccount', 'UA-yyyyyyyy-y']);
_gas.push(['_setAllowAnchor', true]);
_gas.push(['_setAllowLinker', true]);
_gas.push(['_setDomainName', 'domain1.com']);
_gas.push(['_setDomainName', 'domain2.com']);
_gas.push(['_trackPageview']);
_gas.push(['_setMultiDomain', 'click']);
```

This way you make sure both the trackers have the same configurations. Otherwise you can have problems if they share the same cookie and have different settings.

**Comment by KarinaLibrary** [comment]
Hi Eduardo - thanks for the reply.

My understanding of using named trackers (xd._setAccount etc.) is that you
don't want the two trackers to share cookies because that can cause
analytics reporting problems... ? But that is for gaq and maybe with the
gas layer it's different... ?

M.

**Comment by eduardocereto** [comment]
In your case they would share cookies anyway. With or without GAS. It's always a good idea to share cookies. If you create different cookie sets it can be very buggy and has the potential of creating many problems. I don't recommend doing it unless you're 100% sure of how it works and that you really need it.
