### ISSUE TITLE
Switch compiler to uglifyjs

### ISSUE THREAD

**Issue by eduardocereto** [CardinalPath/gas#9]
I'm thinking about switching compilers to uglifyjs. 

I'm having problems with closurecompiler mangling too many variables.

I already implemented it in develop. But I wanted to open this issue to get feedback.

It also feels better to me to have a minifier that is open source and based on javascript instead of closure compiler.

**Comment by phms** [comment]
What is the difference in size between the generated file?

**Comment by eduardocereto** [comment]
I ran some tests and here are the results for the current develop branch.

byte count / gziped byte count
- **closure_compiler with advanced optimizations:** 12,059 / 4,520
- **closure_compiler:** 13,659 / 4,895
- **uglifyjs --unsafe:** 13,613 / 4,994
- **uglifyjs:** 13,626 / 4,995
- **closure_compiler whitespace_only:** 19,671 / 5,828
- **original:** 43,599 / 10,981

**Comment by eduardocereto** [comment]
It's worth noticing that closure ADVANCED removes some code that he categorizes as "dead code", those are functions that are never run on the code and never exported. Some of our helpers fall into this category, most notable the _sanitizeString, so that's why it has some advantage. I'm not even sure if we should have that method anyway.

**Comment by eduardocereto** [comment]
Fixed on branch:develop 386444e6b1
